### ISSUE TITLE
Address initial feedback

### ISSUE THREAD

**Issue by ninpnin** [swerik-project/website#2]
## About

- [x] Instead of “about” it should be “SWERIK”
- [x] Use this image as front image: https://www.umu.se/en/humlab/program-activities/text-mining/
- [x] Change headline to: “Swedish Riksdag 1867–2022: An Ecosystem of Linked Open Data (SWERIK)”
- [x] We use the intro text in the application as presentation text: [SEE EMAIL]
- [x] Delete the summary of news and selected publication
- [x] Main icon – link it to Fredrik's mail address
- [x] At the bottom of the page, there should be icons of the project partners and funders:  Malmö, Uppsala, Riksdagsbiblioteket, RJ

## Blog

- [x] Delete the test blog posts
 
## Publications

- [x] Delete the test publications. My idea is that we can both list publications that have been produced within the project, and publications that relate to the Swerik corpus. I will get back to you on that.
 
## People

- [x] Add everybody's presentations

## Misc

- [x] Use capital a first capital letter for all sub-menu categories (e.g. “About”)
- [x] Add logos for RJ, Malmö University, Uppsala University, Riksdagsbiblioteket
- [x] Delete what is now called “submenus”

**Comment by fredrik1984** [comment]
Would it be possible to have a new version of the webpage ready by the end of next week? Hopefully, I will get the different presentation texts from everyone in the project by then.

**Comment by ninpnin** [comment]
I think I can fix most of these things by then.

**Comment by fredrik1984** [comment]
cool!

**Comment by fredrik1984** [comment]
I just realized that it would be extra good if the webpage would be up on Wednesday next week. I will present the Swerik project at Estonia Digital Memory conference on Thursday, and it would be nice to add the link to the webpage then! Is that possible?

Regarding the webpage link, let's go for "swerik-corpus" since "swerik" is occupied.

**Comment by fredrik1984** [comment]
On the About page: 
- Below the title: change "Infrastructure project" to "Research infrastructure project funded by Riksbankens Jubileumsfond
- Delete "(proposal acronym)" in the body text
- delete the icons for mail and RSS – one will find the contact info on the people page
- delete "You can even add a little note about which of these is the best way to reach you."

**Comment by fredrik1984** [comment]
Also, here comes a first blog post that you can add too:

[Headline:] SWERIK has officially started!

SWERIK started officially on March 1, 2023, the same day when PI Fredrik Mohammadi Norén started his new position as an assistant professor in media and communication at Malmö University. However, the work of curating the Swedish parliamentary speeches has been going on since 2020 within the [Welfare State Analytics project](https://www.westac.se/en/), in which Fredrik, Måns Magnusson, and Väinö Yrjänäinen also work. Hence, a [pilot corpus](https://github.com/welfare-state-analytics/riksdagen-corpus) of parliamentary speeches between 1920–2020 already existed when SWERIK started, with above 90 % estimated accuracy for the identification of speakers. 

Now, we have started to import speech data from 1867 to 1919. In version release 0.7, the corpus includes speech data from 1890 to today. Simultaneously, we continue to build the database with members of parliament (MP). The aim is to soon have all MPs in the database, which is a work we do in collaboration with Wikidata volunteers. Then we will start to add relevant metadata to MPs and improve the mapping of MPs to their speeches in the chambers.

**Comment by fredrik1984** [comment]
The "People" page should be named "Participants" instead. And when you add the descriptions of people and the photos, it would be nice, if possible, to have some layout that looks like this https://www.westac.se/en/participants/ or this https://modernatider1936.se/en/medverkande/
